version: '3.8'

services:
  db:
    image: postgres:13  # Versão específica do PostgreSQL
    container_name: restaurante-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: restaurante
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"  # Mapeia a porta 8080 do contêiner para a porta 8080 do host
      - "8443:8443"  # Adiciona esta linha para expor a porta HTTPS

    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/restaurante  # Usando o nome do serviço 'db' em vez do IP
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
     

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"  # Mapeia a porta 80 do contêiner pgAdmin para a porta 8081 do host
    depends_on:
      - db

volumes:
  db_data:  # Volume persistente para os dados do banco de dados
